### ISSUE TITLE
🏗️ MVP feature tracker

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/pdfje#2]
Features (not exhaustive):
- [x] Full unicode text (not just ASCII)
- [x] Different fonts
- [x] Handle newlines in text
- [x] Wrap text
- [x] Text styles and font families
- [x] Drawing lines and shapes
- [ ] Images
- [ ] translating/scaling/rotating/mirroring
- [ ] bookmarks
- [ ] document metadata
- [x] compression
- [x] better PDF spec compliance
- [x] make `fontTools` dependency optional
- [x] kerning
- [x] automatic page layouts

Out of scope (for now):
- [ ] forms
- [ ] page numbers
- [ ] Table of Contents
- [ ] annotations

**Comment by ariebovenberg** [comment]
Features will now be tracked in roadmap (in readme) and PRs
